

# Generated by Django 4.2.16 on 2025-04-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_message"),
        
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
