# Generated by Django 4.2.16 on 2025-04-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_message_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
