# Generated by Django 4.2.16 on 2025-05-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created"]},
        ),
        migrations.RenameField(
            model_name="review",
            old_name="created_at",
            new_name="created",
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "★"), (2, "★★"), (3, "★★★"), (4, "★★★★"), (5, "★★★★★")]
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.profile"
            ),
        ),
    ]
