# Generated by Django 4.2.16 on 2025-05-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_alter_review_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="app1.listing"
            ),
        ),
    ]
