# Generated by Django 4.2.16 on 2025-05-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_category_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Optional profile picture",
                null=True,
                upload_to="profile_photos/",
            ),
        ),
    ]
